WebApp/Controllers/ArtistController.cs
using Festival_WebApp.Data;
using Festival_WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data.Entity;

namespace Festival_WebApp.Controllers
{
    public class ArtistController : Controller
    {
        private readonly myDbContext db = new myDbContext(); // Replace YourDbContext with your actual DbContext name


        public ActionResult Index()
        {
            var artists = db.Artists.ToList();

            return View(artists);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Artists.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                // If there are validation errors, display the errors
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine("Validation error: " + error.ErrorMessage);
                    }
                }
            }

            return View(artist);
        }

        // GET: Concert/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }




            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine("Validation error: " + error.ErrorMessage);
                    }
                }
            }
            return View(artist);
        }

        // GET: Concert/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Artist artist = db.Artists.Find(id);

            if (artist == null)
            {
                return NotFound();
            }


            return View(artist);
        }
        // GET: Concert/Details/5
        public ActionResult Details(int id)
        {
            var artist = db.Artists.FirstOrDefault(a => a.Id == id);
            if (artist == null)
            {
                return NotFound(); // Or handle not found scenario
            }

            return View(artist); // Pass the Concert to the Details view
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artists.Find(id);
            db.Artists.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/Controllers/ConcertController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Festival_WebApp.Models;
using System.Data.Entity;
using Festival_WebApp.Data;
using System;

namespace Festival_WebApp.Controllers
{
    public class ConcertController : Controller
    {
        private readonly myDbContext db = new myDbContext(); // Replace YourDbContext with your actual DbContext name

        
        public ActionResult Index()
        {
            List<Concert> concerts = db.Concerts.Include(c => c.Artist).ToList();
            ViewBag.concerts = concerts;
                return View();
        }

   
        public ActionResult Create()
        {
            ViewBag.Artists = db.Artists.ToList(); // Retrieve artists for dropdown or selection

            return View();
        }

       [HttpPost]
       [ValidateAntiForgeryToken]
      public async Task<IActionResult> Create([Bind("Title, ArtistId, Date, Description")] Concert concert)
      {

            Console.WriteLine(concert.ArtistId);


            concert.Artist = db.Artists.Find(concert.ArtistId);
            
            if (ModelState.IsValid || !ModelState.IsValid && concert.ArtistId!=null)
          {
              // Fetch selected artist from database
              db.Concerts.Add(concert);
              await db.SaveChangesAsync();
              return RedirectToAction(nameof(Index));
          }
          
          else
            {
                // If there are validation errors, display the errors
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine("Validation error: " + error.ErrorMessage);
                    }
                }
            }
            ModelState.Remove("ArtistId");
            ViewBag.Artists = db.Artists.ToList();
            return View(concert);
        }
      /* [HttpPost]
       [ValidateAntiForgeryToken]
       public ActionResult Create(Concert concert )
       {
           if (ModelState.IsValid)
           {
               db.Concerts.Add(concert);
               db.SaveChanges();
               return RedirectToAction("Index");
           }
           else
           {
               // If there are validation errors, display the errors
               foreach (var modelState in ModelState.Values)
               {
                   foreach (var error in modelState.Errors)
                   {
                       Console.WriteLine("Validation error: " + error.ErrorMessage);
                   }
               }
           }

           return View(concert);
       }*/

        // GET: Concert/Edit/5
        public ActionResult Edit(int? id)

        {
            if (id == null)
            {
                return BadRequest();
            }




            Concert concert = db.Concerts.Find(id);
            if (concert == null)
            {
                return NotFound();
            }
            List<Artist> artists = db.Artists.ToList();

            ViewBag.Artists = artists;
            return View(concert);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Concert concert )
        {
            Console.WriteLine(concert.ArtistId);


            concert.Artist = db.Artists.Find(concert.ArtistId);

            if (ModelState.IsValid || !ModelState.IsValid && concert.ArtistId != null)
            {
                db.Entry(concert).State = (System.Data.Entity.EntityState)EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                // If there are validation errors, display the errors
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine("Validation error: " + error.ErrorMessage);
                    }
                }
            }
            ModelState.Remove("ArtistId");
            ViewBag.Artists = db.Artists.ToList();
            return View(concert);
        }

        // GET: Concert/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Concert concert = db.Concerts.Find(id);

            if (concert == null)
            {
                return NotFound();
            }


            return View(concert);
        }
        // GET: Concert/Details/5
        public ActionResult Details(int id)
        {
            var concert = db.Concerts.FirstOrDefault(a => a.Id == id);
            if (concert == null)
            {
                return NotFound(); // Or handle not found scenario
            }

            return View(concert); // Pass the Concert to the Details view
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Concert concert = db.Concerts.Find(id);
            db.Concerts.Remove(concert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Festival_WebApp</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Festival_WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet"  href="~/lib/jquery-ui/jquery-ui.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Festival_WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Concert" asp-action="Index">Concerts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Festival_WebApp - <a asp-area="" asp-controller="Home">Home </a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>